apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - image: choirulanwar/nestjs-mongo-api
          name: user-service
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    dev.okteto.com/auto-ingress: 'true'
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: 'user-service'
      port: 3000
